## Markup - https://gohugo.io/getting-started/configuration-markup/

highlight:
  anchorLineNos: true
  lineNos: true
  lineNumbersInTable: false
  tabWidth: 2
  style: rose-pine-dawn

tableOfContents:
  endLevel: 3
  ordered: false
  startLevel: 2
