## Markup - https://gohugo.io/getting-started/configuration-markup/

highlight:
  anchorLineNos: true
  lineNos: true
  lineNumbersInTable: false
  tabWidth: 2
  style: rose-pine-dawn

tableOfContents:
  startLevel: 1
  endLevel: 1
  ordered: false
