## Modules https://gohugo.io/hugo-modules/configuration/
# https://github.com/bep/hugo-starter-tailwind-basic

hugoVersion:
  extended: true
  min: 0.120.4
mounts:
  - source: assets
    target: assets
  - source: hugo_stats.json
    target: assets/watching/hugo_stats.json
